 
version: 2
jobs:
 build:
   docker:
     - image: mcopik/clang-dfsan:dfsan-9.0
   steps:
     - checkout
     - run:
        name: Install dependencies
        command: 'apt-get update && apt-get install --no-install-recommends -y cmake libopenmpi-dev git'
     - run:
        name: Install libstdc++
        command: 'apt-get install --no-install-recommends -y libstdc++-7-dev'
     - run:
        name: Install llvm-lit
        command: 'apt-get install --no-install-recommends -y python3-pip && pip3 install lit'
     - run:
        name: Run CMake configuration
        command: 'cmake -B build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLLVM_DIR=/opt/llvm/ -DLIBCXX_PATH=/opt/llvm/ .'
     - run:
        name: Run CMake build
        command: 'cmake --build build'
     - run:
        name: Run tests
        command: 'lit build/tests'

