 
version: 2
jobs:
 build:
   docker:
     - image: mcopik/clang-dfsan:dfsan-9.0
       user: docker
   steps:
     - run:
        name: Install dependencies
        command: 'sudo apt-get update && sudo apt-get install
                  --no-install-recommends -y ninja-build cmake libopenmpi-dev
                  openmpi-bin git ssh'
     - run:
        name: Install libstdc++
        command: 'sudo apt-get install --no-install-recommends -y libstdc++-7-dev'
     - run:
        name: Install llvm-lit
        command: 'sudo apt-get install --no-install-recommends -y
                  python3-setuptools python3-pip && pip3 install wheel &&
                  pip3 install lit'
     - checkout
     - run:
        name: Run CMake configuration
        command: 'mkdir build && cd build &&
                  cmake -G "Ninja"
                    -DCMAKE_C_COMPILER=clang
                    -DCMAKE_CXX_COMPILER=clang++
                    -DLLVM_DIR=/opt/llvm/
                    -DLIBCXX_PATH=/opt/llvm/
                    ..'
     - run:
        name: Run CMake build
        command: 'cd build && ninja nlohmann_json && ninja '
     - run:
        name: Run tests
        command: 'python3 ~/.local/lib/python3.6/site-packages/lit/main.py -v build/tests'

