 
version: 2
 jobs:
   build:
     docker:
       - image: mcopik/clang-dfsan:9.0
     steps:
       - checkout
       - run: echo "A first hello"
       - run: sleep 25
   test:
     docker:
       - image: mcopik/clang-dfsan:9.0
     steps:
       - checkout
       - run: echo "A more familiar hi"
       - run: sleep 15
 workflows:
   version: 2
   one_and_two:
     jobs:
       - build
       - test
